
CREATE TABLE GRUPOS (
idgrupo VARCHAR(4) PRIMARY KEY NOT NULL ,
nombre VARCHAR(20) NOT NULL,
fechaformacion DATE NOT NULL,
numerocomponentes VARCHAR(4) NOT NULL,
pais VARCHAR(20) NOT NULL)

CREATE TABLE DISCOS (
iddisco VARCHAR(4) PRIMARY KEY NOT NULL ,
nombre VARCHAR(20) NOT NULL,
copiasvendidas VARCHAR(10) NOT NULL,
fechapublicacion DATE NOT NULL,
idgrupo VARCHAR(4) NOT NULL,
CONSTRAINT FK_DISCOS_GRUPOS FOREIGN KEY(idgrupo)
REFERENCES GRUPOS(idgrupo) ON DELETE CASCADE)